language: cpp
dist: xenial

matrix:
    include:
        # Ubuntu Linux 16.04 gcc5.4
        - os: linux
          compiler: gcc
          before_install:
              export CXX="g++-5" CC="gcc-5"

        # Apple OSX LLVM version 10.0.0 (clang-1000.11.45.5)
        - os: osx
          osx_image: xcode10.1
          compiler: clang

        # OSX gcc6
        - os: osx
          osx_image: xcode10.1
          compiler: gcc
          before_install:
              - xcode-select --install
              - rm -rf /usr/local/include/c++
              - brew update
              - brew install gcc6
              - export CXX="g++-6" CC="gcc-6"
              - sudo softwareupdate -i "Command Line Tools (macOS High Sierra version 10.13) for Xcode-9.3"

notifications:
  email: false

script:
  - $CXX --version
  
  # Install Eigen3
  # - hg clone https://bitbucket.org/eigen/eigen/
  # - ln -s $HOME/build/vsoftco/qpp/eigen $HOME/eigen
  - wget http://bitbucket.org/eigen/eigen/get/3.3.5.zip -O eigen3.zip
  - unzip -q eigen3.zip 
  - mv eigen-eigen-b3f3d4950030 $HOME/eigen
  
  # Build a minimal example
  - mkdir build
  - cd build
  - cmake .. -DEIGEN3_INCLUDE_DIR=$HOME/eigen -DCMAKE_BUILD_TYPE=Debug && make
  
  # Build the unit tests
  - cd ../unit_tests
  - mkdir build
  - cd build
  - cmake .. -DEIGEN3_INCLUDE_DIR=$HOME/eigen -DCMAKE_BUILD_TYPE=Debug && make

  # Run the unit tests
  - ./tests/qpp_testing --gtest_filter=-qpp_Timer*
