language: cpp
dist: bionic
os: linux

jobs:
  include:
    # Ubuntu Linux 18.04 gcc-7.1
    - os: linux
      compiler: gcc
      before_install:
        - export CXX="g++-7" CC="gcc-7"
        - export BUILD="make"

    # Ubuntu Linux 18.04 clang-7.0
    - os: linux
      compiler: clang
      before_install:
        - sudo apt-get install libc++-dev libc++abi-dev
        - export CXX="clang++" CC="clang"
        - export LD_LIBRARY_PATH=/usr/local/clang/lib:$LD_LIBRARY_PATH
        - export BUILD="make"

    # Apple OSX LLVM version 10.0.0 (clang-1000.11.45.5)
    - os: osx
      osx_image: xcode10.3
      compiler: clang
      before_install:
        - export BUILD="make"

    # Apple OSX gcc-7.5
    - os: osx
      osx_image: xcode10.3
      compiler: gcc
      before_install:
        - rm -rf /usr/local/include/c++
        - brew update
        - brew install gcc@7
        - export CXX="g++-7" CC="gcc-7"
        - export BUILD="make"
        - sudo softwareupdate -i "Command Line Tools (macOS Mojave version 10.14) for Xcode-10.3"

notifications:
  email: false

script:
  - $CXX --version

  # Install Eigen3
  - wget https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.zip -O eigen3.zip && unzip -q eigen3.zip && mv eigen-3.3.7 $HOME/eigen

  # Build the examples
  - mkdir build && cd build && cmake .. -DEIGEN3_INSTALL_DIR=$HOME/eigen -DCMAKE_BUILD_TYPE=Debug && make -j4

  # Build the unit tests
  - cd ../unit_tests && mkdir build && cd build && cmake .. -DEIGEN3_INSTALL_DIR=$HOME/eigen -DCMAKE_BUILD_TYPE=Debug && make -j4

  # Run the unit tests
  - ./tests/qpp_testing --gtest_filter=-qpp_Timer*
