version: 1.0.{build}

image: Visual Studio 2019

platform: x64

environment: 
  EIGEN3_INSTALL_PATH: eigen3
  matrix:
    - compiler: msvc2019
    - compiler: msys2
    
install:
  - ps: wget https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.zip -O eigen3.zip
  - cmd: |-
      unzip eigen3.zip > nul
      mv eigen-3.3.7 "c:\%EIGEN3_INSTALL_PATH%"

build_script:
  - cmd: '%APPVEYOR_BUILD_FOLDER%\.appveyor\appveyor_build.bat'

test_script:
  - cmd: '%APPVEYOR_BUILD_FOLDER%\.appveyor\appveyor_test.bat'
