[build-system]
requires = [
    "pybind11>=2.10.0",
    "setuptools>=42",
    "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "pyqpp"
version = "6.0"
description = "Python 3 wrapper for Quantum++"
authors = [
    { name = "softwareQ Inc.", email = "info@softwareq.ca" },
]
readme = "pyqpp/README.md"
license = { text = "MIT" }
dependencies = [
    "numpy",
]

[project.urls]
homepage = "https://github.com/softwareqinc/qpp"
repository = "https://github.com/softwareqinc/qpp.git"

[tool.setuptools]
py-modules = []
