[project]
name = "pyqpp"
requires-python = ">=3.9"
version = "7.0.0"
description = "Python 3 wrapper for Quantum++"
authors = [
    { name = "softwareQ Inc.", email = "info@softwareq.ca" },
]
readme = "pyqpp/README.md"
license = "MIT"
dependencies = [
    "numpy",
]

[project.urls]
homepage = "https://github.com/softwareqinc/qpp"
repository = "https://github.com/softwareqinc/qpp.git"

[build-system]
requires = [
    "pybind11",
    "setuptools",
    "types-setuptools",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = []
