version: 2.1

# CircleCI doesn't handle large file sets properly for local builds
# https://github.com/CircleCI-Public/circleci-cli/issues/281#issuecomment-472808051
localCheckout: &localCheckout
  run: |-
    PROJECT_PATH=$(cd ${CIRCLE_WORKING_DIRECTORY}; pwd)
    mkdir -p ${PROJECT_PATH}
    cd /tmp/_circleci_local_build_repo
    git ls-files -z | xargs -0 -s 2090860 tar -c | tar -x -C ${PROJECT_PATH}
    cp -a /tmp/_circleci_local_build_repo/.git ${PROJECT_PATH}

jobs:
  ubuntu_bionic:
    description: A template for building and testing Quantum++ on Ubuntu Linux
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout # change this from "checkout" to "*localCheckout" when running CircleCI locally
      - run:
          name: Clone submodules
          command: |
            git submodule update --init
      - run:
          name: Install dependencies (Eigen3)
          command: |
            sudo apt-get update
            sudo apt-get install -y libeigen3-dev
      - run:
          name: Install the library
          command: |
            mkdir build && cd build
            cmake .. -DWITH_EXAMPLES=ON -DWITH_UNIT_TESTS=ON -DCMAKE_BUILD_TYPE=Debug
            sudo make install
      - run:
          name: Compile and run a standalone example
          command: |
            cd examples/standalone && mkdir build && cd build
            cmake .. -DCMAKE_BUILD_TYPE=Debug && make -j4
            ./standalone
      - run:
          name: Build the examples
          command: |
            cd build
            make -j4 examples
      - run:
          name: Build the unit tests
          command: |
            cd build
            make -j4 unit_tests
      - run:
          name: Run the unit tests
          command: |
            cd build
            ctest -E qpp_Timer

  macOS:
    description: A template for building and testing Quantum++ on macOS
    macos:
      xcode: "11.3.0"
    steps:
      - checkout # change this from "checkout" to "*localCheckout" when running CircleCI locally
      - run:
          name: Clone submodules
          command: |
            git submodule update --init
      - run:
          name: Install dependencies (Eigen3)
          command: |
            brew update && brew install eigen
      - run:
          name: Install the library
          command: |
            mkdir build && cd build
            cmake .. -DWITH_EXAMPLES=ON -DWITH_UNIT_TESTS=ON -DCMAKE_BUILD_TYPE=Debug
            sudo make install
      - run:
          name: Compile and run a standalone example
          command: |
            cd examples/standalone && mkdir build && cd build
            cmake .. -DCMAKE_BUILD_TYPE=Debug && make -j4
            ./standalone
      - run:
          name: Build the examples
          command: |
            cd build
            make -j4 examples
      - run:
          name: Build the unit tests
          command: |
            cd build
            make -j4 unit_tests
      - run:
          name: Run the unit tests
          command: |
            cd build
            ctest -E qpp_Timer

workflows:
  build:
    jobs:
      - ubuntu_bionic:
          name: ubuntu-bionic
#     - macOS:
#         name: macOS-base
